apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Action to publish build artifact
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: cloudbees-io/register-build-artifact@v1
        name: Publish artifact
        with:
          name: "myApp"
          version: "1.0.0"
          url: "docker.io/myapp/myimg:1.0.0"
          digest: "sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b3609d"