apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Gradle Build
        uses: docker://eclipse-temurin:21-alpine
        kind: build
        shell: sh
        run: |
          ./gradlew -s clean build;
      - id: dockerconfig
        name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        kind: deploy
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          destination: docker.io/jyoungcb/docker-demo:0.0.1-${{cloudbees.version}}
          verbosity: debug

    # needs:
    #   - Approval
  # Approval:
  #   timeout-minutes: 4320
  #   delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  #   with:
  #     approvers: d20e99a0-7aa9-11ec-a35c-42010a83aeda
  #     disallowLaunchByUser: false
  #     instructions: Approve me please
