apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    outputs:
      output1: ${{ steps.step1.outputs.greeting }}
      output2: ${{ steps.step2.outputs.greeting }}
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Gradle Build
        uses: docker://eclipse-temurin:21-alpine
        kind: build
        shell: sh
        run: |
          ./gradlew -s clean build;
      - id: dockerconfig
        name: Set up Docker Hub registry
        uses: cloudbees-io/configure-oci-credentials@v1
        kind: deploy
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          destination: docker.io/jyoungcb/docker-demo:0.0.1-${{cloudbees.version}}
          verbosity: debug
      
      - name: My first step
        uses: docker://alpine:3.18
        id: step1
        run: echo "hello there" > "$CLOUDBEES_OUTPUTS/greeting"
      
      - name: My second step
        uses: docker://alpine:3.18
        id: step2
        run: echo "from the hive" > "$CLOUDBEES_OUTPUTS/greeting"
        
  my-job-2:
    needs: build
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs.output1}}
          OUTPUT2: ${{needs.build.outputs.output2}}
        uses: docker://alpine:3.18
        run: echo "$OUTPUT1 $OUTPUT2"

    # needs:
    #   - Approval
  # Approval:
  #   timeout-minutes: 4320
  #   delegates: cloudbees-io/manual-approval/custom-job.yml@v1
  #   with:
  #     approvers: d20e99a0-7aa9-11ec-a35c-42010a83aeda
  #     disallowLaunchByUser: false
  #     instructions: Approve me please
