apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - id: dockerconfig
        name: Configure container registry credentials
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build container image with Kaniko
        uses: cloudbees-io/kaniko/.cloudbees/testing
        with:
          destination: docker.io/jyoungcb/docker-demo:0.0.1-${{cloudbees.version}}
          verbosity: debug
          send-artifact-info: true
