apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: skipped-needs
on:
  workflow_dispatch:
jobs:
  job1:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
  job2:
    if: ${{ false }}
    needs: job1
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
